# Generated by Django 6.0 on 2026-02-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CARDIOLOGY', 'CARDIOLOGY'), ('DERMATOLOGY', 'DERMATOLOGY'), ('NEWROLOGY', 'NEWROLOGY'), ('NEPHROLOGY', 'NEPHROLOGY')], max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
