# Generated by Django 6.0 on 2026-02-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_phone_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='phone',
            new_name='patient',
        ),
    ]
