# Generated by Django 6.0 on 2026-02-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_phone_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
