# Generated by Django 6.0 on 2026-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_appointment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
