# Generated by Django 6.0 on 2026-02-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='stetus',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('NOT DONE', 'NOT DONE'), ('DONE', 'DONE')], default='NOT DONE', max_length=100),
        ),
    ]
